### ISSUE TITLE
apparently corrupt data in bucket

### ISSUE THREAD

**Issue by blaggacao** [kostasdizas/aw-watcher-sublime#2]
corrupt data after submitting first heartbeat

```shell
2020-05-26 00:37:37 [INFO ]: Creating bucket 'aw-watcher-sublime'  (aw_datastore.datastore.Datastore:37)
2020-05-26 00:37:48 [INFO ]: Received heartbeat, but bucket was previously empty, inserting as new event. (bucket: aw-watcher-sublime)  (aw_server.api:232)
2020-05-26 00:37:51 [INFO ]: 404 (127.0.0.1): GET /api/0/ HTTP/1.1  (flask:25)
2020-05-26 00:37:58 [INFO ]: 404 (127.0.0.1): GET /api/0/ HTTP/1.1  (flask:25)
Traceback (most recent call last):
  File "aw_query/query2.py", line 126, in interpret
  File "aw_query/functions.py", line 80, in g
  File "aw_query/functions.py", line 106, in g
  File "aw_query/functions.py", line 205, in q2_merge_events_by_keys
  File "aw_transform/merge_events_by_keys.py", line 24, in merge_events_by_keys
TypeError: unhashable type: 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aw_server/rest.py", line 244, in post
  File "aw_server/api.py", line 245, in query2
  File "aw_query/query2.py", line 393, in query
  File "aw_query/query2.py", line 371, in interpret
  File "aw_query/query2.py", line 123, in interpret
  File "aw_query/query2.py", line 128, in interpret
aw_query.exceptions.QueryInterpretException: Tried to call function merge_events_by_keys with invalid amount of arguments
```

**Comment by blaggacao** [comment]
Is it because the name property is empty?
```json
{"buckets": {"aw-watcher-sublime": {"id": "aw-watcher-sublime", "created": "2020-05-26T00:37:37.818217+00:00", "name": null, "type": "app.editor.activity", "client": "aw-watcher-sublime", "hostname": "dar", "events": [{"timestamp": "2020-05-26T00:38:26.841000+00:00", "duration": 0.0, "data": {"project": {"folders": [{"path": "/home/blaggacao/.config/sublime-text-3/Packages/aw-watcher-sublime"}]}, "language": "source.json", "file": "/home/blaggacao/.config/sublime-text-3/Packages/aw-watcher-sublime/Main.sublime-menu"}}, {"timestamp": "2020-05-26T00:37:46.395000+00:00", "duration": 11.133, "data": {"project": {"folders": [{"path": "/home/blaggacao/.config/sublime-text-3/Packages/aw-watcher-sublime"}]}, "language": "source.python", "file": "/home/blaggacao/.config/sublime-text-3/Packages/aw-watcher-sublime/aw-watcher-sublime.py"}}]}}}
```

**Comment by blaggacao** [comment]
Oh no, I think it's the nesting on the project key
